<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus UFT One" productVer="2022" os="Windows 11" host="LAPTOP-UBMQF7FC"><DocLocation><![CDATA[D:\E-Commerce\TestCases\OrderingProduct]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[OrderingProduct]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:27]]></Time>
<TimeTick>1669119027</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:27]]></Time>
<TimeTick>1669119027</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Log in.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:27]]></Time>
<TimeTick>1669119027</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" >
<Disp><![CDATA[Log in.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf45.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf44.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:27]]></Time>
<TimeTick>1669119027</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["harikrishnapara145@gmail.com"]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:28]]></Time>
<TimeTick>1669119028</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="15" >
<Disp><![CDATA[Email.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf47.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" >
<Disp><![CDATA[Demo Web Shop. Login]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf46.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf43.xml]]></Path>
<ASHilite><![CDATA[4326828]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Value - 'harikrishnapara145@gmail.com' entered in Field - 'Email edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:28]]></Time>
<TimeTick>1669119028</TimeTick>
<NodeArgs eType="User" icon="9" nRep="16" status="Passed" >
<Disp><![CDATA[Value - 'harikrishnapara145@gmail.com' entered in Field - 'Email edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:28]]></Time>
<TimeTick>1669119028</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:28]]></Time>
<TimeTick>1669119028</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["DCA@123"]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:28]]></Time>
<TimeTick>1669119028</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" >
<Disp><![CDATA[Password.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf50.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="19" >
<Disp><![CDATA[Demo Web Shop. Login]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf49.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="18" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf48.xml]]></Path>
<ASHilite><![CDATA[4326828]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Value - 'DCA@123' entered in Field - 'Password edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:28]]></Time>
<TimeTick>1669119028</TimeTick>
<NodeArgs eType="User" icon="9" nRep="21" status="Passed" >
<Disp><![CDATA[Value - 'DCA@123' entered in Field - 'Password edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:28]]></Time>
<TimeTick>1669119028</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:28]]></Time>
<TimeTick>1669119028</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Log in.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:28]]></Time>
<TimeTick>1669119028</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="25" >
<Disp><![CDATA[Log in.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf53.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="24" >
<Disp><![CDATA[Demo Web Shop. Login]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf52.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:29]]></Time>
<TimeTick>1669119029</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Cell phones.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:29]]></Time>
<TimeTick>1669119029</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="28" >
<Disp><![CDATA[Cell phones.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf55.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="27" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf54.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Cell phones]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:30]]></Time>
<TimeTick>1669119030</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Add to cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:30]]></Time>
<TimeTick>1669119030</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="31" >
<Disp><![CDATA[Add to cart.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf57.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[shopping cart.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:30]]></Time>
<TimeTick>1669119030</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" >
<Disp><![CDATA[shopping cart.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf58.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="30" >
<Disp><![CDATA[Demo Web Shop. Cell phones]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf56.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:30]]></Time>
<TimeTick>1669119030</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Tricentis Demo Web Shop.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:30]]></Time>
<TimeTick>1669119030</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="35" >
<Disp><![CDATA[Tricentis Demo Web Shop.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf60.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="34" >
<Disp><![CDATA[Demo Web Shop. Shopping]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf59.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="23" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf51.xml]]></Path>
<ASHilite><![CDATA[4326828]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Google Chrome]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:31]]></Time>
<TimeTick>1669119031</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[InsightObject_3.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:31]]></Time>
<TimeTick>1669119031</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="38" >
<Disp><![CDATA[InsightObject_3.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf62.xml]]></Path>
<ASHilite><![CDATA[9]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="37" >
<Disp><![CDATA[Google Chrome]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf61.xml]]></Path>
<ASHilite><![CDATA[4326828]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:32]]></Time>
<TimeTick>1669119032</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:32]]></Time>
<TimeTick>1669119032</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[termsofservice.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:32]]></Time>
<TimeTick>1669119032</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="42" >
<Disp><![CDATA[termsofservice.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf65.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Checkout.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:32]]></Time>
<TimeTick>1669119032</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="44" >
<Disp><![CDATA[Checkout.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf66.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="41" >
<Disp><![CDATA[Demo Web Shop. Shopping]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf64.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Checkout]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:34]]></Time>
<TimeTick>1669119034</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Continue.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:34]]></Time>
<TimeTick>1669119034</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="47" >
<Disp><![CDATA[Continue.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf68.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[PickUpInStore.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:34]]></Time>
<TimeTick>1669119034</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="51" >
<Disp><![CDATA[PickUpInStore.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf69.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Continue_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:35]]></Time>
<TimeTick>1669119035</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="53" >
<Disp><![CDATA[Continue_2.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf70.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[paymentmethod.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Payments.CashOnDelivery"]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:36]]></Time>
<TimeTick>1669119036</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="57" >
<Disp><![CDATA[paymentmethod.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf71.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Continue_3.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:36]]></Time>
<TimeTick>1669119036</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="59" >
<Disp><![CDATA[Continue_3.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf72.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="46" >
<Disp><![CDATA[Demo Web Shop. Checkout]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf67.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="40" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf63.xml]]></Path>
<ASHilite><![CDATA[4326828]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Google Chrome]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:37]]></Time>
<TimeTick>1669119037</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[InsightObject.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:37]]></Time>
<TimeTick>1669119037</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="62" >
<Disp><![CDATA[InsightObject.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf74.xml]]></Path>
<ASHilite><![CDATA[11]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="61" >
<Disp><![CDATA[Google Chrome]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf73.xml]]></Path>
<ASHilite><![CDATA[4326828]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:37]]></Time>
<TimeTick>1669119037</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Order Details]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:37]]></Time>
<TimeTick>1669119037</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[In-Store Pickup.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:37]]></Time>
<TimeTick>1669119037</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="67" >
<Disp><![CDATA[In-Store Pickup.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf77.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="66" >
<Disp><![CDATA[Demo Web Shop. Order Details]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf76.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Checkout]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:37]]></Time>
<TimeTick>1669119037</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:38]]></Time>
<TimeTick>1669119038</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="70" >
<Disp><![CDATA[Confirm.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf79.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="69" >
<Disp><![CDATA[Demo Web Shop. Checkout]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf78.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:38]]></Time>
<TimeTick>1669119038</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Log out.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[22-11-2022 - 17:40:38]]></Time>
<TimeTick>1669119038</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="73" >
<Disp><![CDATA[Log out.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf81.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="72" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf80.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="65" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf75.xml]]></Path>
<ASHilite><![CDATA[4326828]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="22-11-2022 - 17:40:27" eTime="22-11-2022 - 17:40:38" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[OrderingProduct Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="22-11-2022 - 17:40:23" eTime="22-11-2022 - 17:40:38" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test OrderingProduct Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>